version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VERSION
        - SERVICE
    image: ${REGISTRY:-local}/baikal/${SERVICE}:${VERSION:-snapshot}
    environment:
        # TODO: Review WHY the dependencies are not downloaded during docker build time in CI
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    env_file:
      - docker-compose.env
    volumes:
      - .:/opt/app:delegated
      - ./samples/out:/datasets-out
