{
	"namespace": "com.telefonica.urm.Customer.General",
	"name": "Consent_State_Candidate",
	"type": "record",
	"doc": "Consent State Candidate. This dataset is intended for purposes of \"OB's consents total sync\", and only with that aim.",
	"x-fp-version": "6.0.0",
	"x-fp-avro4p-version": "1.5",
	"x-fp-join-definitions": {
		"join00001": {"dataset_id": "D_Consent_Purpose", "dataset_version": 6, "fields": ["PURPOSE_ID"]},
		"join00002": {"dataset_id": "D_Gbl_Brand", "dataset_version": 6, "fields": ["GBL_BRAND_ID"]}
	},
	"fields": [
		{"name": "CONSENT_ID", "aliases": ["id"], "type": "string", "x-fp-unique-constraints": [1], "doc": "Identifier for a consent"},
		{"name": "USER_4P_ID", "aliases": ["user_id"], "type": {"type": "string", "x-fp-user-id": true, "x-fp-data-protection": "pseudonymize"}, "doc": "Identifier of the user in the Kernel Platform (as returned by the OB in the Kernel Platform APIs)"},
		{"name": "LEGAL_ENTITY_ID", "aliases": ["legal_entity_id"], "type": "string", "doc": "The legal entity for which the user gave consent to"},
		{"name": "PURPOSE_ID", "aliases": ["purpose_id"], "type": "string", "x-fp-join": [{"join_id": "join00001", "field": "PURPOSE_ID"}], "doc": "Identifier of the purpose associated with the consent.\n\nA purpose_id identifies a legal basis for the consent, and restricts the usage of the requested information to the user only for those scenarios covered under the purpose definition"},
		{"name": "IDENTIFIER_REC", "aliases": ["identifier"], "type": ["null", {"name": "IDENTIFIER_REC_RECORD", "type": "record", "namespace": "com.telefonica.urm.Customer.General.Consent_State_Candidate", "fields": [
			{"name": "IDENTIFIER_TYPE_CD", "aliases": ["type"], "type": {"name": "IDENTIFIER_TYPE_CD_ENUM", "namespace": "com.telefonica.urm.Customer.General.Consent_State_Candidate.IDENTIFIER_REC", "type": "enum", "symbols":["phone_number", "email", "uid"]}, "doc": "Identifier type"},
			{"name": "IDENTIFIER_ID", "aliases": ["id"], "type": {"type": "string", "x-fp-data-protection": "pseudonymize"}, "doc": "User identifier.\n\n\n\nDepending on the consent data source, the content of this field is different. The type of content for the current record is indicated in the field USER_TYPE_CD.\n\n\n\nTo be used to search the user associated to an identifier value. It must be used along with IDENTIFIER_TYPE_CD.\n\nFormat will be a phone-number, email or uid, depeding on the value of the IDENTIFIER_TYPE_CD (enum).\n\nFor phone-number, 'E164 with +' format must be used.\n\n### Example\n\nThe content of this field can be IMSI_ID, PHONE_ID (MSISDN_ID for mobile phones or fixed phone number), CLIENT_IP_DES, SUBSCRIBER_ID..."}
		]}], "doc": "User identifier record.\n\n\n\nIt must be used along with IDENTIFIER_TYPE_CD.\n\n\n\nThe scope of a consent can be restricted to a specific identifier that the user has (e.g. just on of his cell phone numbers). If this field is null then the consent applies to all possible identifiers\n\n### Additional Information\n\nFor phone-number, 'E164 with +' format must be used."},
		{"name": "CONSENT_STATUS_CD", "aliases": ["status"], "type": {"name": "CONSENT_STATUS_CD_ENUM", "namespace": "com.telefonica.urm.Customer.General.Consent_State_Candidate", "type": "enum", "symbols":["Active", "Expired", "Revoked", "Prompted"]}, "doc": "The status of the consent. The only status that allows accessing the user's information is \"Active\"\n\n- active: means the consent is granted and it can be used by applications to access personal information.\n\n- prompted: means consent was presented to the user but the user doesn't still accepted that.\n\n- revoked: means that the user actively denied consent.\n\n- expired: means the consent had been granted but is now not usable because the current date is greater than the expiration date of that consent."},
		{"name": "CREATION_TM", "aliases": ["creation_date"], "type": {"type": "string", "logicalType": "datetime", "x-fp-time-dimension": "logicalType"}, "doc": "The creation date-time of the consent"},
		{"name": "EXPIRATION_TM", "aliases": ["expiration_date"], "type": ["null", {"type": "string", "logicalType": "datetime"}], "doc": "The expiration date-time of the consent. Consents that do not expire will have a null value in this field.\n\nA consent with \"Active\" value, even if it is not overwritten, will be considered as \"Expired\" if the expiration date is exceeded."},
		{"name": "USER_PROMPTED_TM", "aliases": ["user_prompted"], "type": ["null", {"type": "string", "logicalType": "datetime"}], "default": null, "doc": "The date-time of the consent last time that the consent request was shown to the user. If the consent request has never been shown to the user, then null"},
		{"name": "CHANNEL_ID", "aliases": ["channel"], "type": ["null", "string"], "doc": "Channel identifier. It indicates the channel through which the consent has been captured."},
		{"name": "REASON_DES", "aliases": ["reason"], "type": ["null", "string"], "default": null, "doc": "Reason description. Free field to convey the reason why the end user granted this consent."},
		{"name": "BRAND_ID", "aliases": ["brand_id"], "type": "string", "x-fp-join": [{"join_id": "join00002", "field": "GBL_BRAND_ID"}], "doc": "Commercial brand global identifier (codified according to D_Gbl_Brand); in order to differentiate among different brands in the same OB"},
		{"name": "TRIGGERED_BY_DES", "aliases": ["triggered_by_des"], "type": "string", "doc": "Name of the process that launched the creation of a consent"},
		{"name": "DELEGATED_IND", "aliases": ["delegated_ind"], "type": "boolean", "default": false, "doc": "Flag indicator to mark if the consent has been delegated to a third party"},
		{"name": "KERNEL_APP_ID", "aliases": ["kernel_app_id"], "type": ["null", "string"], "doc": "Identifier (ID) of the Kernel App to whitch the consent is granted. If null, the consent applies to all the legal entity."}
	]
}
